//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMF.DataAccess
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class TMF_Meter_ReadingsEntities : DbContext
    {
        public TMF_Meter_ReadingsEntities()
            : base("name=TMF_Meter_ReadingsEntities")
        {
        }

        public TMF_Meter_ReadingsEntities(string connString)
            : base(connString)
        {
                
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<DMZ> DMZs { get; set; }
        public virtual DbSet<Gateway> Gateways { get; set; }
        public virtual DbSet<GatewayLog> GatewayLogs { get; set; }
        public virtual DbSet<LatestMeterReading> LatestMeterReadings { get; set; }
        public virtual DbSet<Meter> Meters { get; set; }
        public virtual DbSet<MeterProtocol> MeterProtocols { get; set; }
        public virtual DbSet<MeterReading> MeterReadings { get; set; }
        public virtual DbSet<MeterSize> MeterSizes { get; set; }
        public virtual DbSet<MeterType> MeterTypes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
    }
}
